//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "blockchain_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub tx_hash: String,
    pub block_number: i32,
    pub log_index: i32,
    pub event_type: String,
    pub contract_address: String,
    pub network: String,
    pub user_address: Option<String>,
    pub amount: Option<Decimal>,
    pub quantity: Option<Decimal>,
    pub timestamp: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
