//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coins_historical_prices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub coin_id: String,
    pub symbol: String,
    pub date: Date,
    pub price: Decimal,
    pub market_cap: Option<Decimal>,
    pub volume: Option<Decimal>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
