//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "crypto_listings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub coin_id: String,
    pub symbol: String,
    pub token_name: String,
    pub exchange: String,
    pub trading_pair: String,
    pub listing_announcement_date: Option<DateTime>,
    pub listing_date: Option<DateTime>,
    pub delisting_announcement_date: Option<DateTime>,
    pub delisting_date: Option<DateTime>,
    pub status: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
