//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "daily_prices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub index_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    pub price: Decimal,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub quantities: Option<Json>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
