//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "historical_prices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub coin_id: String,
    pub symbol: String,
    pub timestamp: i32,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
