//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "index_metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub index_id: i32,
    pub category: Option<String>,
    pub asset_class: Option<String>,
    pub token_ids: Vec<i32>,
    pub name: String,
    pub symbol: String,
    pub address: String,
    pub initial_date: Option<Date>,
    pub initial_price: Option<Decimal>,
    pub coingecko_category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub exchanges_allowed: Option<Json>,
    pub exchange_trading_fees: Option<Decimal>,
    pub exchange_avg_spread: Option<Decimal>,
    pub rebalance_period: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rebalances::Entity")]
    Rebalances,
}

impl Related<super::rebalances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rebalances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
