//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "index_constituents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub index_id: i32,
    pub coin_id: String,
    pub token_symbol: String,
    pub token_name: String,
    pub exchange: String,
    pub trading_pair: String,
    pub position: i32,
    pub added_at: Option<DateTime>,
    pub removed_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::index_metadata::Entity",
        from = "Column::IndexId",
        to = "super::index_metadata::Column::IndexId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IndexMetadata,
}

impl Related<super::index_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IndexMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
