//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "index_metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub index_id: i32,
    pub category: Option<String>,
    pub asset_class: Option<String>,
    pub token_ids: Vec<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
