//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rebalances")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub index_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub coins: Json,
    pub portfolio_value: Decimal,
    pub total_weight: Decimal,
    pub timestamp: i64,
    pub rebalance_type: String,
    pub deployed: Option<bool>,
    pub deployed_at: Option<DateTime>,
    pub tx_hash: Option<String>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::index_metadata::Entity",
        from = "Column::IndexId",
        to = "super::index_metadata::Column::IndexId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IndexMetadata,
}

impl Related<super::index_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IndexMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
